---
- name: Base configuration
  hosts: k3s_cluster
  roles:
    - common

- name: Worker data disk
  hosts: k3s_workers
  roles:
    - worker_storage

- name: K3s server
  hosts: k3s_masters
  roles:
    - k3s_server

- name: K3s agent
  hosts: k3s_workers
  roles:
    - k3s_agent
